language: node_js

node_js:
  - 12.10.0

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install
  - make install

before_script:
  - make lint

script:
  - make mode=example

after_script:
  - make integration-test
