language: node_js

node_js:
  - 12.10.0

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install
  - make install

script:
  - make env=example

before_script:
  - make lint

after_success:
  - make integration-test
