name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'Build')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Install dependencies
        run: make install
      - name: Build application
        run: make all ENV=prod

